<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFcbUjru\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFcbUjru/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFcbUjru.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFcbUjru\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFcbUjru\App_KernelDevDebugContainer([
    'container.build_hash' => 'FcbUjru',
    'container.build_id' => 'e55e401d',
    'container.build_time' => 1588257131,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFcbUjru');
